### PR TITLE
fix oxmysql

### PR DESCRIPTION
**Pull request by jaylac2000**

### CODE REVIEW

**Review by iTrulx — APPROVED** [review]
Nice One

**Comment by IceBreak21** [comment]
does the update you done work or no

**Comment by jaylac2000** [comment]
Yeah... works for me

**Comment by iTrulx** [comment]
@IceBreak21 Worked for me too but you could just try running it yourself...

**Comment by IceBreak21** [comment]
so im kinda new here so what should i replace

**Comment by iTrulx** [comment]
@IceBreak21 You can just go to this link [here](https://github.com/Slimeemils/mrp-paychecks/pull/4/commits/7167c64078891883ecb5f8369d976e8efcf0850b) and replace the lines of code needed, it will tell you which file has been edited and what has been removed and added.

**Comment by IceBreak21** [comment]
okay i done that but now its telling me i dont have a job when i have a job called mechanic

**Comment by IceBreak21** [comment]
it dont work for me

**Comment by iTrulx** [comment]
@IceBreak21 A photo of the error would be helpful.

**Comment by Slimeemils** [comment]
Sorry for the long time before the merge. I kinda forgot I had posted this even.

**Pull request merged**
